# Generated by Django 5.1.5 on 2026-03-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('avg_tuition_usd', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country_of_residence', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('english_score', models.FloatField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('course_interest', models.CharField(blank=True, max_length=200)),
                ('recommended_country', models.CharField(blank=True, max_length=100)),
                ('recommended_course', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('applied', 'Applied'), ('visa_process', 'Visa Process'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('source', models.CharField(default='ai_assessment', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('tuition_usd', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=100)),
                ('field_of_interest', models.CharField(max_length=200)),
                ('preferred_countries', models.JSONField(default=list)),
                ('budget_range', models.CharField(max_length=100)),
                ('english_proficiency', models.CharField(max_length=50)),
                ('work_experience_years', models.IntegerField(default=0)),
                ('target_intake', models.CharField(max_length=50)),
                ('additional_info', models.TextField(blank=True)),
                ('ai_country_recommendation', models.JSONField(default=list)),
                ('ai_course_recommendation', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='api.lead')),
            ],
        ),
    ]
