# Generated by Django 5.1.5 on 2026-08-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'permissions': [('can_delete_lead', 'Can delete lead records'), ('can_export_leads', 'Can export lead data')]},
        ),
    ]
