# Generated by Django 5.1.5 on 2026-10-04 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_WORKFLOWS = [
    {
        'name': 'United Kingdom Study Application',
        'country': ('United Kingdom', 'GB', ('United Kingdom', 'UK'), ('GB', 'UK')),
        'steps': [
            'University application submitted',
            'University review',
            'Offer received',
            'Tuition deposit paid',
            'CAS issued',
            'Student visa application',
            'Visa decision',
            'Pre-departure preparation',
        ],
    },
    {
        'name': 'Canada Study Application',
        'country': ('Canada', 'CA', ('Canada',), ('CA',)),
        'steps': [
            'University application submitted',
            'University review',
            'Offer received',
            'Tuition deposit paid',
            'Provincial attestation / study permit documents',
            'Study permit application',
            'Visa decision',
            'Pre-departure preparation',
        ],
    },
    {
        'name': 'Australia Study Application',
        'country': ('Australia', 'AU', ('Australia',), ('AU',)),
        'steps': [
            'University application submitted',
            'University review',
            'Offer received',
            'Tuition deposit paid',
            'Confirmation of Enrolment issued',
            'Student visa application',
            'Visa decision',
            'Pre-departure preparation',
        ],
    },
    {
        'name': 'United States Study Application',
        'country': (
            'United States',
            'US',
            ('United States', 'United States of America', 'USA', 'US'),
            ('US', 'USA'),
        ),
        'steps': [
            'University application submitted',
            'University review',
            'Offer received',
            'I-20 issued',
            'SEVIS fee paid',
            'Student visa interview',
            'Visa decision',
            'Pre-departure preparation',
        ],
    },
    {
        'name': 'Germany Study Application',
        'country': ('Germany', 'DE', ('Germany',), ('DE',)),
        'steps': [
            'University application submitted',
            'University review',
            'Offer received',
            'Admission confirmation received',
            'Financial proof prepared',
            'Student visa application',
            'Visa decision',
            'Pre-departure preparation',
        ],
    },
]


def seed_default_workflows(apps, schema_editor):
    Country = apps.get_model('api', 'Country')
    CountryWorkflow = apps.get_model('api', 'CountryWorkflow')
    CountryWorkflowStep = apps.get_model('api', 'CountryWorkflowStep')
    database = schema_editor.connection.alias

    for definition in DEFAULT_WORKFLOWS:
        canonical_name, code, name_aliases, code_aliases = definition['country']
        name_filter = models.Q()
        for alias in name_aliases:
            name_filter |= models.Q(name__iexact=alias)
        code_filter = models.Q()
        for alias in code_aliases:
            code_filter |= models.Q(code__iexact=alias)
        matches = Country.objects.using(database).filter(name_filter | code_filter)
        candidate_ids = set(matches.values_list('pk', flat=True))
        if len(candidate_ids) > 1:
            raise RuntimeError(
                f"Multiple Country records match the default workflow for {canonical_name}; "
                'resolve the catalogue records before applying this migration.'
            )

        if candidate_ids:
            country = Country.objects.using(database).get(pk=candidate_ids.pop())
        else:
            country = Country.objects.using(database).create(
                name=canonical_name,
                code=code,
                description='Study abroad destination.',
                highlights=[],
                avg_tuition_usd=0,
                is_popular=True,
            )

        workflow = CountryWorkflow.objects.using(database).filter(
            country_id=country.pk,
            active=True,
        ).first()
        if workflow is None:
            workflow = CountryWorkflow.objects.using(database).create(
                country_id=country.pk,
                name=definition['name'],
                active=True,
            )

        existing_orders = set(
            CountryWorkflowStep.objects.using(database)
            .filter(workflow_id=workflow.pk)
            .values_list('order', flat=True)
        )
        for order, step_name in enumerate(definition['steps'], start=1):
            if order not in existing_orders:
                CountryWorkflowStep.objects.using(database).create(
                    workflow_id=workflow.pk,
                    name=step_name,
                    order=order,
                    required=True,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='api.country')),
            ],
            options={
                'ordering': ['country__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CountryWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.countryworkflow')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationWorkflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_progress', to='api.application')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_application_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_progress', to='api.countryworkflowstep')),
            ],
            options={
                'ordering': ['workflow_step__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='countryworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('country',), name='unique_active_country_workflow'),
        ),
        migrations.AddConstraint(
            model_name='countryworkflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='unique_country_workflow_step_order'),
        ),
        migrations.AddConstraint(
            model_name='applicationworkflowprogress',
            constraint=models.UniqueConstraint(fields=('application', 'workflow_step'), name='unique_application_workflow_progress'),
        ),
        migrations.RunPython(seed_default_workflows, migrations.RunPython.noop),
    ]
