# Generated by Django 5.1.5 on 2026-10-05 11:04

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TEMPLATES = [
    {
        'name': 'United Kingdom Default Application Documents',
        'country': ('United Kingdom', ('United Kingdom', 'UK'), ('GB', 'UK')),
        'requirements': [
            ('passport', 'Passport'),
            ('academic_transcripts', 'Academic Transcripts'),
            ('english_language_certificate', 'English Language Certificate'),
            ('personal_statement', 'Personal Statement'),
            ('financial_documents', 'Financial Documents'),
        ],
    },
    {
        'name': 'Canada Default Application Documents',
        'country': ('Canada', ('Canada',), ('CA',)),
        'requirements': [
            ('passport', 'Passport'),
            ('academic_transcripts', 'Academic Transcripts'),
            ('english_language_certificate', 'English Language Certificate'),
            ('financial_documents', 'Financial Documents'),
            ('study_permit_supporting_documents', 'Study Permit / Supporting Documents'),
        ],
    },
    {
        'name': 'Australia Default Application Documents',
        'country': ('Australia', ('Australia',), ('AU',)),
        'requirements': [
            ('passport', 'Passport'),
            ('academic_transcripts', 'Academic Transcripts'),
            ('english_language_certificate', 'English Language Certificate'),
            ('financial_documents', 'Financial Documents'),
            ('genuine_student_supporting_documents', 'Genuine Student / Supporting Documents'),
        ],
    },
    {
        'name': 'United States Default Application Documents',
        'country': (
            'United States',
            ('United States', 'United States of America', 'USA', 'US'),
            ('US', 'USA'),
        ),
        'requirements': [
            ('passport', 'Passport'),
            ('academic_transcripts', 'Academic Transcripts'),
            ('english_language_certificate', 'English Language Certificate'),
            ('financial_documents', 'Financial Documents'),
            ('statement_supporting_documents', 'Statement / Supporting Documents'),
        ],
    },
    {
        'name': 'Germany Default Application Documents',
        'country': ('Germany', ('Germany',), ('DE',)),
        'requirements': [
            ('passport', 'Passport'),
            ('academic_transcripts', 'Academic Transcripts'),
            ('english_german_language_certificate', 'English/German Language Certificate'),
            ('financial_proof', 'Financial Proof'),
            ('admission_documents', 'Admission Documents'),
        ],
    },
]

DEFAULT_DESCRIPTION = (
    'Default platform checklist item. Confirm the current requirements with the '
    'relevant institution and authorities; this is not legal or immigration advice.'
)


def seed_document_templates(apps, schema_editor):
    Country = apps.get_model('api', 'Country')
    CountryDocumentTemplate = apps.get_model('api', 'CountryDocumentTemplate')
    CountryDocumentRequirement = apps.get_model('api', 'CountryDocumentRequirement')
    Application = apps.get_model('api', 'Application')
    ApplicationDocumentRequirement = apps.get_model('api', 'ApplicationDocumentRequirement')
    database = schema_editor.connection.alias

    for definition in DEFAULT_TEMPLATES:
        country_name, name_aliases, code_aliases = definition['country']
        name_filter = models.Q()
        for alias in name_aliases:
            name_filter |= models.Q(name__iexact=alias)
        code_filter = models.Q()
        for alias in code_aliases:
            code_filter |= models.Q(code__iexact=alias)
        candidate_ids = set(
            Country.objects.using(database)
            .filter(name_filter | code_filter)
            .values_list('pk', flat=True)
        )
        if len(candidate_ids) > 1:
            raise RuntimeError(
                f"Multiple Country records match the default document template for {country_name}; "
                'resolve the catalogue records before applying this migration.'
            )
        if candidate_ids:
            country_id = candidate_ids.pop()
        else:
            country_id = Country.objects.using(database).create(
                name=country_name,
                code={'United Kingdom': 'GB', 'Canada': 'CA', 'Australia': 'AU',
                      'United States': 'US', 'Germany': 'DE'}[country_name],
                description='Study abroad destination.',
                highlights=[],
                avg_tuition_usd=0,
                is_popular=True,
            ).pk

        template = CountryDocumentTemplate.objects.using(database).filter(
            country_id=country_id,
            active=True,
        ).first()
        if template is None:
            template = CountryDocumentTemplate.objects.using(database).create(
                country_id=country_id,
                name=definition['name'],
                active=True,
            )

        for order, (document_type, label) in enumerate(definition['requirements'], start=1):
            template_requirement, _ = CountryDocumentRequirement.objects.using(database).get_or_create(
                template_id=template.pk,
                document_type=document_type,
                defaults={
                    'label': label,
                    'description': DEFAULT_DESCRIPTION,
                    'required': True,
                    'order': order,
                },
            )
            for application in Application.objects.using(database).filter(country_id=country_id):
                ApplicationDocumentRequirement.objects.using(database).get_or_create(
                    application_id=application.pk,
                    template_id=template.pk,
                    document_type=document_type,
                    defaults={
                        'template_requirement_id': template_requirement.pk,
                        'label': template_requirement.label,
                        'description': template_requirement.description,
                        'required': template_requirement.required,
                        'order': template_requirement.order,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_countryworkflow_countryworkflowstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='api.country')),
            ],
            options={
                'ordering': ['country__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CountryDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.countrydocumenttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='api.application')),
                ('student_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_requirements', to='api.studentdocument')),
                ('template_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='api.countrydocumentrequirement')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='api.countrydocumenttemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='countrydocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('country',), name='unique_active_country_document_template'),
        ),
        migrations.AddConstraint(
            model_name='countrydocumentrequirement',
            constraint=models.UniqueConstraint(fields=('template', 'document_type'), name='unique_template_document_type'),
        ),
        migrations.AddConstraint(
            model_name='countrydocumentrequirement',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_template_document_order'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocumentrequirement',
            constraint=models.UniqueConstraint(fields=('application', 'template', 'document_type'), name='unique_application_template_document_type'),
        ),
        migrations.RunPython(seed_document_templates, migrations.RunPython.noop),
    ]
