# Generated by Django 5.1.5 on 2026-10-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_countryworkflow_countryworkflowstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('conditional', 'Conditional'), ('unconditional', 'Unconditional'), ('scholarship', 'Scholarship')], default='conditional', max_length=30)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, default='')),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.application')),
                ('offer_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_offers', to='api.studentdocument')),
            ],
            options={
                'ordering': ['-received_date', '-created_at', 'id'],
            },
        ),
    ]
