# Generated by Django 5.1.5 on 2026-10-06 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_countrydocumenttemplate_countrydocumentrequirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('conditional', 'Conditional Offer'), ('unconditional', 'Unconditional Offer'), ('deferred', 'Deferred Offer')], default='conditional', max_length=30)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=30)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_deadline', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('conditions', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('offer_code', models.CharField(blank=True, default='', max_length=80)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.application')),
                ('offer_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_links', to='api.studentdocument')),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('offer_code__gt', '')), fields=('application', 'offer_code'), name='unique_application_offer_code')],
            },
        ),
    ]
