# Generated by Django 5.1.5 on 2026-10-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_applicationoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(choices=[('student_visa', 'Student Visa'), ('dependent_visa', 'Dependent Visa'), ('other', 'Other')], default='student_visa', max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('preparing', 'Preparing'), ('submitted', 'Submitted'), ('appointment_scheduled', 'Appointment Scheduled'), ('biometrics_completed', 'Biometrics Completed'), ('decision_pending', 'Decision Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='not_started', max_length=30)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('biometrics_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_case', to='api.application')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
    ]
