# Generated by Django 5.1.5 on 2026-10-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_visacase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('enrolled', 'Enrolled'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, default='', max_length=200)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('intake', models.CharField(blank=True, default='', max_length=50)),
                ('student_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='api.application')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
    ]
